import { Album } from "~/models/Album";
import { PopularPlaylist } from "~/models/PopularPlaylist";
import { RecentlyPlayed } from "~/models/RecentlyPlayed";
import { UserArtist } from "~/models/UserArtist";

export const newReleasesMock: Album[] = [
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/70kkdajctXSbqSMJbQO424",
        },
        href: "https://api.spotify.com/v1/artists/70kkdajctXSbqSMJbQO424",
        id: "70kkdajctXSbqSMJbQO424",
        name: "Kacey Musgraves",
        type: "artist",
        uri: "spotify:artist:70kkdajctXSbqSMJbQO424",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AM",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BD",
      "BE",
      "BG",
      "BH",
      "BI",
      "BN",
      "BT",
      "BW",
      "BY",
      "CH",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GE",
      "GR",
      "HK",
      "HR",
      "HU",
      "ID",
      "IL",
      "IN",
      "IT",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LI",
      "LK",
      "LS",
      "LT",
      "LU",
      "LV",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "MN",
      "MO",
      "MT",
      "MU",
      "MV",
      "MW",
      "MY",
      "MZ",
      "NA",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PW",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SM",
      "SZ",
      "TH",
      "TL",
      "TO",
      "TR",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "UZ",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
      "AO",
      "BJ",
      "CM",
      "DZ",
      "GA",
      "GB",
      "GQ",
      "IE",
      "MA",
      "NE",
      "NG",
      "PT",
      "TD",
      "TN",
      "BF",
      "CI",
      "GH",
      "GM",
      "GN",
      "GW",
      "IS",
      "LR",
      "ML",
      "MR",
      "SL",
      "SN",
      "ST",
      "TG",
      "CV",
      "AR",
      "BR",
      "SR",
      "UY",
      "AG",
      "BB",
      "BO",
      "BS",
      "CA",
      "CL",
      "CW",
      "DM",
      "DO",
      "GD",
      "GY",
      "HT",
      "KN",
      "LC",
      "PY",
      "TT",
      "US",
      "VC",
      "CO",
      "EC",
      "JM",
      "MX",
      "PA",
      "PE",
      "BZ",
      "CR",
      "GT",
      "HN",
      "NI",
      "SV",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/4d4qaLHCcfXzMbGa33Kpqg",
    },
    href: "https://api.spotify.com/v1/albums/4d4qaLHCcfXzMbGa33Kpqg",
    id: "4d4qaLHCcfXzMbGa33Kpqg",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273a14ab07a55d5f690eff8531f",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02a14ab07a55d5f690eff8531f",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851a14ab07a55d5f690eff8531f",
        width: 64,
      },
    ],
    name: "justified",
    release_date: "2021-08-27",
    release_date_precision: "day",
    total_tracks: 1,
    type: "album",
    uri: "spotify:album:4d4qaLHCcfXzMbGa33Kpqg",
  },
  {
    album_type: "single",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/70kkdajctXSbqSMJbQO424",
        },
        href: "https://api.spotify.com/v1/artists/70kkdajctXSbqSMJbQO424",
        id: "70kkdajctXSbqSMJbQO424",
        name: "Kacey Musgraves",
        type: "artist",
        uri: "spotify:artist:70kkdajctXSbqSMJbQO424",
      },
    ],
    available_markets: [
      "AD",
      "AE",
      "AL",
      "AM",
      "AT",
      "AU",
      "AZ",
      "BA",
      "BD",
      "BE",
      "BG",
      "BH",
      "BI",
      "BN",
      "BT",
      "BW",
      "BY",
      "CH",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "EE",
      "EG",
      "ES",
      "FI",
      "FJ",
      "FM",
      "FR",
      "GE",
      "GR",
      "HK",
      "HR",
      "HU",
      "ID",
      "IL",
      "IN",
      "IT",
      "JO",
      "JP",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LI",
      "LK",
      "LS",
      "LT",
      "LU",
      "LV",
      "MC",
      "MD",
      "ME",
      "MG",
      "MH",
      "MK",
      "MN",
      "MO",
      "MT",
      "MU",
      "MV",
      "MW",
      "MY",
      "MZ",
      "NA",
      "NL",
      "NO",
      "NP",
      "NR",
      "NZ",
      "OM",
      "PG",
      "PH",
      "PK",
      "PL",
      "PS",
      "PW",
      "QA",
      "RO",
      "RS",
      "RU",
      "RW",
      "SA",
      "SB",
      "SC",
      "SE",
      "SG",
      "SI",
      "SK",
      "SM",
      "SZ",
      "TH",
      "TL",
      "TO",
      "TR",
      "TV",
      "TW",
      "TZ",
      "UA",
      "UG",
      "UZ",
      "VN",
      "VU",
      "WS",
      "XK",
      "ZA",
      "ZM",
      "ZW",
      "AO",
      "BJ",
      "CM",
      "DZ",
      "GA",
      "GB",
      "GQ",
      "IE",
      "MA",
      "NE",
      "NG",
      "PT",
      "TD",
      "TN",
      "BF",
      "CI",
      "GH",
      "GM",
      "GN",
      "GW",
      "IS",
      "LR",
      "ML",
      "MR",
      "SL",
      "SN",
      "ST",
      "TG",
      "CV",
      "AR",
      "BR",
      "SR",
      "UY",
      "AG",
      "BB",
      "BO",
      "BS",
      "CA",
      "CL",
      "CW",
      "DM",
      "DO",
      "GD",
      "GY",
      "HT",
      "KN",
      "LC",
      "PY",
      "TT",
      "US",
      "VC",
      "CO",
      "EC",
      "JM",
      "MX",
      "PA",
      "PE",
      "BZ",
      "CR",
      "GT",
      "HN",
      "NI",
      "SV",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/4d4qaLHCcfXzMbGa33Kpqg",
    },
    href: "https://api.spotify.com/v1/albums/4d4qaLHCcfXzMbGa33Kpqg",
    id: "4d4qaLHCcfXzMbGa33Kpaqg",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273a14ab07a55d5f690eff8531f",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02a14ab07a55d5f690eff8531f",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851a14ab07a55d5f690eff8531f",
        width: 64,
      },
    ],
    name: "justified",
    release_date: "2021-08-27",
    release_date_precision: "day",
    total_tracks: 1,
    type: "album",
    uri: "spotify:album:4d4qaLHCcfXzMbGa33Kpqg",
  },
];

export const recentlyPlayedMock: RecentlyPlayed[] = [
  {
    context: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/278ZYwGhdK6QTzE3MFePnP",
      },
      href: "https://api.spotify.com/v1/artists/278ZYwGhdK6QTzE3MFePnP",
      type: "artist",
      uri: "spotify:artist:278ZYwGhdK6QTzE3MFePnP",
    },
    played_at: "2021-08-27T20:07:28.835Z",
    track: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/278ZYwGhdK6QTzE3MFePnP",
            },
            href: "https://api.spotify.com/v1/artists/278ZYwGhdK6QTzE3MFePnP",
            id: "278ZYwGhdK6QTzE3MFePnP",
            name: "Trivium",
            type: "artist",
            uri: "spotify:artist:278ZYwGhdK6QTzE3MFePnP",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0aXIJYbWk4u41iJmoJmp8y",
        },
        href: "https://api.spotify.com/v1/albums/0aXIJYbWk4u41iJmoJmp8y",
        id: "0aXIJYbWk4u41iJmoJmp8y",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab67616d0000b273f11a218563f0edfa7940fc94",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67616d00001e02f11a218563f0edfa7940fc94",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab67616d00004851f11a218563f0edfa7940fc94",
            width: 64,
          },
        ],
        name: "What The Dead Men Say",
        release_date: "2020-04-24",
        release_date_precision: "day",
        total_tracks: 10,
        type: "album",
        uri: "spotify:album:0aXIJYbWk4u41iJmoJmp8y",
      },
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/278ZYwGhdK6QTzE3MFePnP",
          },
          href: "https://api.spotify.com/v1/artists/278ZYwGhdK6QTzE3MFePnP",
          id: "278ZYwGhdK6QTzE3MFePnP",
          name: "Trivium",
          type: "artist",
          uri: "spotify:artist:278ZYwGhdK6QTzE3MFePnP",
        },
      ],
      available_markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW",
      ],
      disc_number: 1,
      duration_ms: 285522,
      explicit: false,
      external_ids: {
        isrc: "NLA322000002",
      },
      external_urls: {
        spotify: "https://open.spotify.com/track/4KugBNgb6iilXInnWQrMVh",
      },
      href: "https://api.spotify.com/v1/tracks/4KugBNgb6iilXInnWQrMVh",
      id: "4KugBNgb6iilXInnWQrMVh",
      is_local: false,
      name: "What The Dead Men Say",
      popularity: 54,
      preview_url:
        "https://p.scdn.co/mp3-preview/538902733c5dde52d78c292a8aaf23394927dc61?cid=f22d961f548f4442936ba5257dc37f88",
      track_number: 2,
      type: "track",
      uri: "spotify:track:4KugBNgb6iilXInnWQrMVh",
    },
  },
  {
    context: {
      external_urls: {
        spotify: "https://open.spotify.com/artist/278ZYwGhdK6QTzE3MFePnP",
      },
      href: "https://api.spotify.com/v1/artists/278ZYwGhdK6QTzE3MFePnP",
      type: "artist",
      uri: "spotify:artist:278ZYwGhdK6QTzE3MFePnP",
    },
    played_at: "2021-08-27T20:02:42.773Z",
    track: {
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/278ZYwGhdK6QTzE3MFePnP",
            },
            href: "https://api.spotify.com/v1/artists/278ZYwGhdK6QTzE3MFePnP",
            id: "278ZYwGhdK6QTzE3MFePnP",
            name: "Trivium",
            type: "artist",
            uri: "spotify:artist:278ZYwGhdK6QTzE3MFePnP",
          },
        ],
        available_markets: [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW",
        ],
      },
    },
  },
];

export const userTopArtistsMock: UserArtist[] = [
  {
    external_urls: {
      spotify: "https://open.spotify.com/artist/6O7MpKrY91vlCd4Osi6XKs",
    },
    followers: {
      total: 1563051,
    },
    genres: ["alternative metal", "modern rock", "pop punk", "screamo"],
    href: "https://api.spotify.com/v1/artists/6O7MpKrY91vlCd4Osi6XKs",
    id: "6O7MpKrY91vlCd4Osi6XKs",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab6761610000e5eb56c59b51661237eb3e3b75f1",
        width: 640,
      },
      {
        height: 320,
        url: "https://i.scdn.co/image/ab6761610000517456c59b51661237eb3e3b75f1",
        width: 320,
      },
      {
        height: 160,
        url: "https://i.scdn.co/image/ab6761610000f17856c59b51661237eb3e3b75f1",
        width: 160,
      },
    ],
    name: "Black Veil Brides",
    popularity: 67,
    type: "artist",
    uri: "spotify:artist:6O7MpKrY91vlCd4Osi6XKs",
  },
  {
    external_urls: {
      spotify: "https://open.spotify.com/artist/1Ffb6ejR6Fe5IamqA5oRUF",
    },
    followers: {
      total: 3934210,
    },
    genres: ["melodic metalcore", "metalcore", "rock", "uk metalcore"],
    href: "https://api.spotify.com/v1/artists/1Ffb6ejR6Fe5IamqA5oRUF",
    id: "1Ffb6ejR6Fe5IamqA5oRUF",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab6761610000e5eb2321fdfa1ed8144ee0271eb6",
        width: 640,
      },
      {
        height: 320,
        url: "https://i.scdn.co/image/ab676161000051742321fdfa1ed8144ee0271eb6",
        width: 320,
      },
      {
        height: 160,
        url: "https://i.scdn.co/image/ab6761610000f1782321fdfa1ed8144ee0271eb6",
        width: 160,
      },
    ],
    name: "Bring Me The Horizon",
    popularity: 80,
    type: "artist",
    uri: "spotify:artist:1Ffb6ejR6Fe5IamqA5oRUF",
  },
];

export const popularPlaylistsMock: PopularPlaylist[] = [
  {
    collaborative: false,
    description:
      "Os lançamentos dessa semana incluem João Gomes, Manu Gavassi, Dilsinho e mais!",
    external_urls: {
      spotify: "https://open.spotify.com/playlist/37i9dQZF1DX34KNiFQJNVm",
    },
    href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX34KNiFQJNVm",
    id: "37i9dQZF1DX34KNiFQJNVm",
    images: [
      {
        url: "https://i.scdn.co/image/ab67706f000000039a334ecdc594a7cb75aebbf5",
      },
    ],
    name: "Novidades da Semana",
    owner: {
      display_name: "Spotify",
      external_urls: {
        spotify: "https://open.spotify.com/user/spotify",
      },
      href: "https://api.spotify.com/v1/users/spotify",
      id: "spotify",
      type: "user",
      uri: "spotify:user:spotify",
    },
    snapshot_id:
      "MTYzMDA3NDU3MywwMDAwMDUwMzAwMDAwMTdiODgwNDEzNTMwMDAwMDE3YjgzYjZiMWY4",
    tracks: {
      href: "https://api.spotify.com/v1/playlists/37i9dQZF1DX34KNiFQJNVm/tracks",
      total: 75,
    },
    type: "playlist",
    uri: "spotify:playlist:37i9dQZF1DX34KNiFQJNVm",
  },
  {
    collaborative: false,
    description:
      "Disfruta de esta experiencia relajante. / Aproveite essa experiência única e relaxe.",
    external_urls: {
      spotify: "https://open.spotify.com/playlist/37i9dQZF1DWZeXxACCcUmL",
    },
    href: "https://api.spotify.com/v1/playlists/37i9dQZF1DWZeXxACCcUmL",
    id: "37i9dQZF1DWZeXxACCcUmL",
    images: [
      {
        url: "https://i.scdn.co/image/ab67706f00000003546468d2fdbe17cd7a5bb300",
      },
    ],
    name: "Soul.House.Relax",
    owner: {
      display_name: "Spotify",
      external_urls: {
        spotify: "https://open.spotify.com/user/spotify",
      },
      href: "https://api.spotify.com/v1/users/spotify",
      id: "spotify",
      type: "user",
      uri: "spotify:user:spotify",
    },
    snapshot_id:
      "MTYyNTA0OTkwNSwwMDAwMDA0MzAwMDAwMTdhNWM4NWI5ZjcwMDAwMDE2Y2Y2OGY4ZGFm",
    tracks: {
      href: "https://api.spotify.com/v1/playlists/37i9dQZF1DWZeXxACCcUmL/tracks",
      total: 141,
    },
    type: "playlist",
    uri: "spotify:playlist:37i9dQZF1DWZeXxACCcUmL",
  },
];
